### ISSUE TITLE
export contact responsible of biobanks

### ISSUE THREAD

**Issue by nmalservet** [Biobanques/ebiobanques#24]
export the emails of contacts responsibles of biobanks into one excel sheet
one cell by email.
feature for admin only

**Comment by mpenicaud** [comment]
Done in searchCatalogController : (export xls catalog)
Must be elsewhere?

**Comment by nmalservet** [comment]
Yes. In the admin part, contacts list.

**Comment by mpenicaud** [comment]
add all contacts (quality, responsible...
