### ISSUE TITLE
Clean confused or inappropriate datas on biobank datas

### ISSUE THREAD

**Issue by mpenicaud** [Biobanques/ebiobanques#53]
confused datas in collection_name and collection_id fields : most of time duplicated data, sometimes one is just truncate of the other, sometimes completely inappropriate data.
After that harmonize with different views

**Comment by nmalservet** [comment]
collection_id = internal id of the collection into the biobank ( example collec32, tumors, etc.) Must be understandable by the biobank publishing the samples
collection_name = explicit name for external usages. (example : brain tumor collection, etc.)
Must be understandable by the researchers to know on which thematics fields the biobank works.
> Todo : add explanation on fields updatable into the admin page of biobank and into the "mybiobank" module

**Comment by nmalservet** [comment]
Better : make the reference with collection_id and collection name with Miabis ( copy the definition and link to miabis)

**Comment by nmalservet** [comment]
https://github.com/MIABIS/miabis/wiki/Data-describing-Sample-Collection

**Comment by nmalservet** [comment]
Perfect. Nice job.
