### ISSUE TITLE
debug and enhance sample smart search

### ISSUE THREAD

**Issue by mpenicaud** [Biobanques/ebiobanques#54]
smart search is bugged : example doesn't work (male 35years).

**Comment by mpenicaud** [comment]
Probably needs of all rewriting the smart search feature instead of only debug this example.

**Comment by mpenicaud** [comment]
Unwanted behavior : after smart search, expression field value is assignated to some fields in advanced search form.

**Comment by nmalservet** [comment]
Mayeb we need to use a better design, with texte search in mongodb and indexes

**Comment by nmalservet** [comment]
Probably a problem into the age comparator

**Comment by nmalservet** [comment]
Finally we can inactivate this tool due to his low interest

**Comment by nmalservet** [comment]
comment the display of this smart search and activate by default the advanced research
