### ISSUE TITLE
Biobanks : labels

### ISSUE THREAD

**Issue by mpenicaud** [Biobanques/ebiobanques#76]
- Le champ « nom de la collection » n’est pas forcément pertinent pour nous : en effet, souvent les biobanques sont multi-thématiques. 
Donc : serait-il possible 
- d’’inverser les colonnes : diagnostic disponible et nom de la collection ?
- de remplacer le nom de « diagnostic disponible » par « aire thérapeutique »
- de remplacer le nom de « Nom de la collection » par «  pathologie »
- de remplacer le code CIM (Classification Internationale des Maladies) par l’aire thérapeutique à laquelle il est relié :
Voici le détail : 

Code CIM / Aire thérapeutique
A00-B99 Maladies infectieuses, parasitaires, VIH
C00-D48 Cancer
D50-D89 Maladies du sang
E00-E90 Maladies endocriniennes, nutritionnelles & métaboliques
F00-G99 Maladies du système nerveux central 
H00-H59 Maladies oculaires
H60-H95 Maladies ORL
I00-I99 Maladies du cœur des vaisseaux
J00-J99 Maladies de l'appareil respiratoire
K00-K93 Maladies de l'appareil digestif
L00-L99 Maladies dermatologiques
M00-M99 Maladies du système ostéo-musculaire
N00-N99 Maladies génitales et urinaires
O00-O99 Grossesse & accouchement
P00-P96 Pédiatrie
Q00-Q99 Malformations congénitales
R00-Z99 Autres

**Comment by nmalservet** [comment]
Done in 1.8.6
